-- Vetzone IQ database schema — v3 (PostgreSQL)
-- Ported from the original SQLite schema.sql. Table/column names, types,
-- and constraints are unchanged except: AUTOINCREMENT -> IDENTITY, and
-- REAL -> DOUBLE PRECISION (same practical behavior, more standard on PG).

CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT
);

-- Atomic ID-allocation counters (P001, V002, IC003, ...). Replaces the old
-- MAX(id)+1-in-Python approach, which was not safe under concurrent use.
CREATE TABLE IF NOT EXISTS id_counters (
    prefix TEXT PRIMARY KEY,
    next_val INTEGER NOT NULL DEFAULT 1
);

-- History of nightly/manual database backups, shown in Settings.
CREATE TABLE IF NOT EXISTS backup_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TEXT NOT NULL,
    finished_at TEXT,
    status TEXT NOT NULL CHECK (status IN ('running','success','failed')),
    filepath TEXT,
    filesize_bytes BIGINT,
    error TEXT,
    triggered_by TEXT  -- 'manual' / 'nightly' / 'shutdown' — NULL for older rows predating this column
);
CREATE INDEX IF NOT EXISTS idx_backup_log_started ON backup_log(started_at);

CREATE TABLE IF NOT EXISTS restore_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TEXT NOT NULL,
    finished_at TEXT,
    status TEXT NOT NULL CHECK (status IN ('success','failed')),
    source_file TEXT,
    error TEXT,
    triggered_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_restore_log_started ON restore_log(started_at);


-- ============================================================ AUTH / USERS / ROLES
-- Roles are no longer a fixed 3-value list. Admin is the one system role
-- (is_system=1) — locked, always has every permission, can't be renamed/
-- deleted. Every other role (including the seeded Vet/Reception) is an
-- ordinary custom role: rename it, delete it, edit its permission
-- checklist and discount cap freely.
CREATE TABLE IF NOT EXISTS roles (
    id TEXT PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    description TEXT,
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    discount_cap INTEGER NOT NULL DEFAULT 0 CHECK (discount_cap BETWEEN 0 AND 100),
    -- Whether staff with this role can be assigned as the attending vet
    -- (Appointments grid, New Visit, Grooming, Inpatient). Deliberately a
    -- role attribute rather than a hardcoded role NAME check, so renaming
    -- or restructuring the "Vet" role can't silently empty every vet
    -- picker in the app the way it used to.
    is_vet_role BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TEXT NOT NULL
);

-- Static seed list of every permission key the app understands — not
-- admin-editable itself, just the fixed vocabulary of what *can* be gated.
-- Kept in sync with auth.PERMISSIONS on every launch.
CREATE TABLE IF NOT EXISTS permissions (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    category TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id TEXT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id TEXT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    full_name TEXT NOT NULL,
    role_id TEXT NOT NULL REFERENCES roles(id),
    custom_discount_cap INTEGER CHECK (custom_discount_cap BETWEEN 0 AND 100),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role_id);

CREATE TABLE IF NOT EXISTS login_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    username TEXT,
    success INTEGER NOT NULL,
    timestamp TEXT NOT NULL,
    ip TEXT,
    user_agent TEXT
);

CREATE TABLE IF NOT EXISTS audit_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    username TEXT,
    timestamp TEXT NOT NULL,
    action TEXT NOT NULL,          -- 'create' / 'update' / 'delete'
    table_name TEXT NOT NULL,
    record_id TEXT NOT NULL,
    field TEXT,
    old_value TEXT,
    new_value TEXT
);
CREATE INDEX IF NOT EXISTS idx_audit_ts ON audit_log(timestamp);

-- ============================================================ OWNERS / PATIENTS
CREATE TABLE IF NOT EXISTS owners (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    address TEXT,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS patients (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    animal_name TEXT,
    species TEXT,
    sex TEXT,
    age_note TEXT,
    repro_status TEXT,
    housing TEXT,
    notes TEXT,
    FOREIGN KEY (owner_id) REFERENCES owners(id)
);
CREATE INDEX IF NOT EXISTS idx_patients_owner ON patients(owner_id);

-- ============================================================ DISTRIBUTORS / PRICE LIST / INVENTORY
CREATE TABLE IF NOT EXISTS distributors (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    contact_person TEXT,
    phone TEXT,
    email TEXT,
    catalog_link TEXT,
    lead_time_days INTEGER,
    payment_terms TEXT,
    notes TEXT
);

-- ============================================================ DISTRIBUTOR LEDGER
-- Manual bookkeeping only — lump-sum bills logged by hand and payments
-- against them, same shape as the owner-side billing/payments pattern
-- elsewhere in this file (a charge row, a separate payments-against-it
-- table, balance computed as charge minus Sum(payments), never stored).
-- Not linked to inventory, POS, or any report — every bill here is a
-- manual entry, not auto-created from anything.
CREATE TABLE IF NOT EXISTS distributor_bills (
    id TEXT PRIMARY KEY,                 -- allocated via next_id(db, "DB")
    distributor_id TEXT NOT NULL,
    bill_date DATE NOT NULL,
    bill_reference TEXT,                 -- the distributor's own paper/invoice number, optional
    total_amount DOUBLE PRECISION NOT NULL CHECK (total_amount >= 0),
    notes TEXT,
    created_at TEXT NOT NULL,
    created_by TEXT,
    FOREIGN KEY (distributor_id) REFERENCES distributors(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_distbills_distributor ON distributor_bills(distributor_id);

CREATE TABLE IF NOT EXISTS distributor_bill_payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL CHECK (amount > 0),
    payment_date DATE NOT NULL,
    method TEXT,                         -- free text: 'Cash', 'Bank Transfer', etc.
    notes TEXT,
    created_at TEXT NOT NULL,
    created_by TEXT,
    FOREIGN KEY (bill_id) REFERENCES distributor_bills(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_distpayments_bill ON distributor_bill_payments(bill_id);

-- Inventory Catalog: Medical / Retail
-- (Declared before Price List: price_list.linked_item_id has an inline FK
-- into this table, and an inline FOREIGN KEY requires the referenced table
-- to already exist at CREATE TABLE time — unlike a later ALTER TABLE ADD
-- CONSTRAINT, table creation order here is load-bearing.)
CREATE TABLE IF NOT EXISTS inventory_list (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Medical' CHECK (category IN ('Medical','Retail')),
    unit TEXT,
    track_expiry BOOLEAN NOT NULL DEFAULT TRUE,
    cost_price DOUBLE PRECISION,
    distributor_id TEXT,
    -- 'Owned' (you bought this stock outright — the default) or
    -- 'Consignment' (a distributor's stock, sitting on your shelf; you
    -- owe them cost_price per unit only once it sells). Only meaningful
    -- for category='Retail' — enforced in app.py, not here, matching how
    -- barcode_source's mutual-exclusivity below is also app-enforced.
    -- For a Consignment item, cost_price keeps its existing meaning
    -- (per-unit cost) but the *payee* changes: it's what's owed to
    -- distributor_id, not what the clinic itself paid — same column,
    -- same downstream COGS math, different real-world counterparty.
    ownership_type TEXT NOT NULL DEFAULT 'Owned' CHECK (ownership_type IN ('Owned','Consignment')),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    barcode TEXT UNIQUE,
    -- Which of the two mutually-exclusive ways this item's barcode was set
    -- up: a real code entered/scanned in from the manufacturer's own
    -- packaging, or one Vetzone IQ generated internally. NULL alongside a
    -- NULL barcode when neither has ever been set up. Never both at once —
    -- enforced in app.py, not just here.
    barcode_source TEXT CHECK (barcode_source IN ('manual','generated')),
    notes TEXT,
    FOREIGN KEY (distributor_id) REFERENCES distributors(id)
);

-- Price List: Service / Medicine / Retail
-- Medicine billing lines are priced by range and do NOT touch inventory stock.
-- Only Retail rows (optionally linked to an inventory item) are sold via POS and move stock.
CREATE TABLE IF NOT EXISTS price_list (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Service' CHECK (category IN ('Service','Medicine','Retail')),
    cost_price DOUBLE PRECISION,
    sale_price DOUBLE PRECISION,
    notes TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    linked_item_id TEXT,             -- Retail rows only: links to inventory_list.id for POS
    can_discount BOOLEAN NOT NULL DEFAULT FALSE,   -- if false, a bill containing this item can't have a discount applied
    FOREIGN KEY (linked_item_id) REFERENCES inventory_list(id)
);

-- ============================================================ AUDITS (whole-catalog Save/Confirm sessions)
-- One session = one shelf-walk. "Not Started Yet" is simply the absence of a session
-- for a date; a session becomes 'Confirmed' (locked, can't be edited) the moment the
-- user presses Confirm, otherwise it stays 'Draft' ("Saved") and can be resumed/edited.
-- Only Confirmed sessions count toward Inventory Status / Ordering Sheet history.
CREATE TABLE IF NOT EXISTS audit_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_date DATE NOT NULL,
    performed_by TEXT,
    status TEXT NOT NULL DEFAULT 'Draft' CHECK (status IN ('Draft','Confirmed')),
    created_at TEXT NOT NULL,
    confirmed_at TEXT,
    FOREIGN KEY (performed_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS audit_session_lines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id INTEGER NOT NULL,
    item_id TEXT NOT NULL,
    stock_counted DOUBLE PRECISION,
    received_since_prior DOUBLE PRECISION NOT NULL DEFAULT 0,
    reorder_threshold DOUBLE PRECISION,          -- NULL = inherit from the last confirmed audit
    critical_item INTEGER,           -- NULL = inherit
    target_coverage_days DOUBLE PRECISION,       -- NULL = inherit
    nearest_expiry_date DATE,
    notes TEXT,
    FOREIGN KEY (session_id) REFERENCES audit_sessions(id),
    FOREIGN KEY (item_id) REFERENCES inventory_list(id),
    -- One line per item per session — app.py's _save_audit_lines() does
    -- INSERT ... ON CONFLICT (session_id, item_id) DO UPDATE against
    -- this, so two concurrent saves for the same session+item update the
    -- same row instead of racing to both insert.
    UNIQUE (session_id, item_id)
);
CREATE INDEX IF NOT EXISTS idx_auditlines_session ON audit_session_lines(session_id);
CREATE INDEX IF NOT EXISTS idx_auditlines_item ON audit_session_lines(item_id);

-- Real-time stock movement — ONLY from POS Retail sales (not Medicine billing).
CREATE TABLE IF NOT EXISTS inventory_transactions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id TEXT NOT NULL,
    change_qty DOUBLE PRECISION NOT NULL,
    reason TEXT NOT NULL,            -- 'sale' / 'manual_adjustment' / 'refund' /
                                      -- 'consignment_receipt' / 'shrinkage' / 'consignment_return'
    ref_id TEXT,
    timestamp TEXT NOT NULL,
    user_id TEXT,
    FOREIGN KEY (item_id) REFERENCES inventory_list(id)
);
CREATE INDEX IF NOT EXISTS idx_invtxn_item ON inventory_transactions(item_id);

-- ============================================================ VISITS (visit + wellness + grooming, one record)
CREATE TABLE IF NOT EXISTS visits (
    id TEXT PRIMARY KEY,
    patient_id TEXT NOT NULL,
    visit_type TEXT,                  -- 'Outpatient' / 'Inpatient'
    date DATE,
    doctor TEXT,                      -- free text, populated from a Vet-user dropdown on new entries
    weight_kg DOUBLE PRECISION,       -- patient's weight at this visit, in kilograms
    bcs INTEGER CHECK (bcs BETWEEN 1 AND 9),   -- Body Condition Score, 1-9 scale
    complaint TEXT,
    history TEXT,
    exam TEXT,
    treatment TEXT,
    case_status TEXT NOT NULL DEFAULT 'Needs Filling'
        CHECK (case_status IN ('Needs Filling','Ongoing','Admitted to Inpatient','Deceased/Euthanized',
                                'Lost to Follow Up','Resolved','Referred')),
    case_status_changed_at TEXT,      -- drives the 2-week "Lost to Follow Up" missed-flag clock
    updates_log TEXT,

    -- Follow-up (method, not type)
    followup_needed TEXT,             -- 'Y' / 'N'
    followup_method TEXT,             -- 'Physical Visit' / 'Phone Call'
    followup_reason TEXT,
    followup_date DATE,
    followup_status TEXT,             -- 'Pending' / 'Completed' / 'Cancelled' / 'N/A'

    -- Wellness reminder
    wellness_needed TEXT DEFAULT 'N',
    wellness_type TEXT,                -- 'Annual Vaccine' / 'Rabies Vaccine' / 'Deworming' / 'Spot On/Pill'
    wellness_next_dose_date DATE,
    wellness_contacted TEXT DEFAULT 'N',
    wellness_contact_method TEXT,      -- 'Phone Call' / 'Message'

    -- Grooming
    grooming_needed TEXT DEFAULT 'N',
    grooming_services TEXT,            -- comma-separated service names
    grooming_notes TEXT,
    grooming_admitted_items TEXT,
    grooming_status TEXT,              -- 'Waiting' / 'Ongoing' / 'Finished'
    grooming_contacted TEXT DEFAULT 'N',

    payment_status TEXT,               -- derived/display cache; real status computed from payments
    created_by TEXT,
    FOREIGN KEY (patient_id) REFERENCES patients(id)
);
CREATE INDEX IF NOT EXISTS idx_visits_patient ON visits(patient_id);
CREATE INDEX IF NOT EXISTS idx_visits_date ON visits(date);

-- Billing: Automatic (priced line items) OR Manual (single lump amount)
CREATE TABLE IF NOT EXISTS billing (
    visit_id TEXT PRIMARY KEY,
    billing_type TEXT NOT NULL DEFAULT 'Automatic' CHECK (billing_type IN ('Automatic','Manual')),
    -- codes column removed — Automatic billing is driven entirely by
    -- visit_billing_lines (price_id + quantity rows), not a comma string.
    manual_amount DOUBLE PRECISION,               -- Manual: single lump sum, exported as one "Veterinary Services" line
    date_billed DATE,
    discount_percent DOUBLE PRECISION NOT NULL DEFAULT 0,
    discount_applied_by TEXT,
    notes TEXT,
    -- The final, 250-rounded payable figure for this bill (what
    -- compute_bill_totals() actually charges), kept in sync by
    -- logic.refresh_visit_billing_total() every time lines/discount/
    -- manual_amount change. Reports read this instead of re-deriving
    -- subtotal*(1-discount%), which would drift from the receipt by up
    -- to ~125 IQD once 250-rounding is applied.
    total DOUBLE PRECISION NOT NULL DEFAULT 0,
    FOREIGN KEY (visit_id) REFERENCES visits(id)
);

-- ============================================================ BOARDING
-- Relies on the existing Patient/Owner records — a boarding session just
-- links to a patient_id, the same way a Visit or Inpatient case does.
-- (Declared before Payments: payments.boarding_id has an inline FK into
-- this table, which requires the referenced table to already exist at
-- CREATE TABLE time.)
CREATE TABLE IF NOT EXISTS boarding_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id TEXT NOT NULL,
    entry_date DATE NOT NULL,
    dismissal_date DATE,              -- expected/actual end date; editable if the stay is extended or shortened
    admitted_items TEXT,
    special_needs BOOLEAN NOT NULL DEFAULT FALSE,   -- chronic disease or custom requirement flag
    special_needs_notes TEXT,
    room TEXT,
    price_per_day DOUBLE PRECISION,
    total DOUBLE PRECISION,           -- raw subtotal (price_per_day * nights, or entered manually) — pre-rounding
    -- The final, 250-rounded payable figure (what compute_bill_totals()
    -- actually charges on `total` above), kept in sync by
    -- logic.refresh_boarding_total() every time the session is saved.
    -- Reports read this instead of the raw `total`, which would drift
    -- from the receipt by up to ~125 IQD once 250-rounding is applied.
    billed_total DOUBLE PRECISION,
    dismissed BOOLEAN NOT NULL DEFAULT FALSE,   -- has the animal actually left yet
    created_by TEXT,
    FOREIGN KEY (patient_id) REFERENCES patients(id)
);
CREATE INDEX IF NOT EXISTS idx_boarding_patient ON boarding_sessions(patient_id);

-- "Something's Wrong!" incident log for a boarding stay
CREATE TABLE IF NOT EXISTS boarding_incidents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    boarding_id INTEGER NOT NULL,
    timestamp TEXT NOT NULL,
    issue TEXT NOT NULL,
    contacted TEXT NOT NULL DEFAULT 'N',        -- 'Y' / 'N'
    contact_method TEXT,                        -- 'Phone Call' / 'Text Message'
    response TEXT,
    user_id TEXT,
    FOREIGN KEY (boarding_id) REFERENCES boarding_sessions(id)
);
CREATE INDEX IF NOT EXISTS idx_boardingincidents_boarding ON boarding_incidents(boarding_id);

-- ============================================================ INPATIENT SYSTEM
-- inpatient_cases is declared here (ahead of inpatient_updates/contact_log/
-- billing below, which logically belong to this same section) because
-- payments.inpatient_case_id has an inline FK into it, which requires the
-- referenced table to already exist at CREATE TABLE time.
CREATE TABLE IF NOT EXISTS inpatient_cases (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id TEXT NOT NULL,
    visit_id TEXT,
    complaint TEXT,
    exam_findings TEXT,
    weight_kg DOUBLE PRECISION,       -- patient's weight at admission, in kilograms
    bcs INTEGER CHECK (bcs BETWEEN 1 AND 9),   -- Body Condition Score, 1-9 scale
    admission_date DATE NOT NULL,
    admitted_items TEXT,
    dismissed BOOLEAN NOT NULL DEFAULT FALSE,
    dismissal_date DATE,
    attending_vet_id TEXT,
    supervising_vet_id TEXT,
    discount_percent DOUBLE PRECISION NOT NULL DEFAULT 0,
    discount_applied_by TEXT,
    created_by TEXT,
    -- The final, 250-rounded payable figure for this case (what
    -- compute_bill_totals() actually charges), kept in sync by
    -- logic.refresh_inpatient_total() every time procedures/discount
    -- change. Reports read this instead of re-deriving revenue from raw
    -- line math, which would drift from the receipt by up to ~125 IQD
    -- once 250-rounding is applied.
    total DOUBLE PRECISION NOT NULL DEFAULT 0,
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (visit_id) REFERENCES visits(id),
    FOREIGN KEY (attending_vet_id) REFERENCES users(id),
    FOREIGN KEY (supervising_vet_id) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_inpatient_patient ON inpatient_cases(patient_id);

CREATE TABLE IF NOT EXISTS payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id TEXT,
    inpatient_case_id INTEGER,
    boarding_id INTEGER,
    amount DOUBLE PRECISION NOT NULL,
    method TEXT,
    date DATE NOT NULL,
    user_id TEXT,
    notes TEXT,
    -- All four nullable — a payment fills in exactly ONE of visit_id /
    -- inpatient_case_id / boarding_id (NULL always satisfies a foreign
    -- key regardless of match, so this only constrains whichever one is
    -- actually set). No ON DELETE CASCADE: nothing in this app
    -- hard-deletes a visit/inpatient case/boarding session/user, so the
    -- default ON DELETE RESTRICT is what we want — the database should
    -- refuse a delete that would orphan payment history, not silently
    -- allow or cascade-destroy it.
    FOREIGN KEY (visit_id) REFERENCES visits(id),
    FOREIGN KEY (inpatient_case_id) REFERENCES inpatient_cases(id),
    FOREIGN KEY (boarding_id) REFERENCES boarding_sessions(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_payments_visit ON payments(visit_id);
CREATE INDEX IF NOT EXISTS idx_payments_case ON payments(inpatient_case_id);
CREATE INDEX IF NOT EXISTS idx_payments_boarding ON payments(boarding_id);

CREATE TABLE IF NOT EXISTS inpatient_updates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id INTEGER NOT NULL,
    timestamp TEXT NOT NULL,
    note TEXT NOT NULL,
    user_id TEXT,
    FOREIGN KEY (case_id) REFERENCES inpatient_cases(id)
);
CREATE INDEX IF NOT EXISTS idx_inpupdates_case ON inpatient_updates(case_id);

CREATE TABLE IF NOT EXISTS inpatient_contact_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id INTEGER NOT NULL,
    timestamp TEXT NOT NULL,
    picked_up INTEGER NOT NULL,
    staff_user_id TEXT,
    notes TEXT,
    FOREIGN KEY (case_id) REFERENCES inpatient_cases(id)
);
CREATE INDEX IF NOT EXISTS idx_inpcontact_case ON inpatient_contact_log(case_id);

CREATE TABLE IF NOT EXISTS inpatient_billing (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id INTEGER NOT NULL,
    price_id TEXT NOT NULL,
    quantity DOUBLE PRECISION NOT NULL DEFAULT 1,
    -- Price/cost snapshotted at the moment this line was added — so a
    -- later Price List edit can't retroactively change what an
    -- already-billed stay owes, or this month's revenue/COGS report for
    -- an already-logged procedure. unit_cost stays nullable: not every
    -- price_list row necessarily has a cost_price set (Services
    -- typically don't carry a COGS basis).
    unit_price DOUBLE PRECISION,
    unit_cost DOUBLE PRECISION,
    logged_by TEXT,
    timestamp TEXT NOT NULL,
    FOREIGN KEY (case_id) REFERENCES inpatient_cases(id),
    FOREIGN KEY (price_id) REFERENCES price_list(id)
);
CREATE INDEX IF NOT EXISTS idx_inpbilling_case ON inpatient_billing(case_id);

-- ============================================================ FILE ATTACHMENTS
CREATE TABLE IF NOT EXISTS attachments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id TEXT NOT NULL,
    visit_id TEXT,
    inpatient_case_id INTEGER,
    relative_path TEXT NOT NULL,
    original_name TEXT NOT NULL,
    uploaded_at TEXT NOT NULL,
    uploaded_by TEXT,
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (visit_id) REFERENCES visits(id),
    FOREIGN KEY (inpatient_case_id) REFERENCES inpatient_cases(id),
    FOREIGN KEY (uploaded_by) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_attach_patient ON attachments(patient_id);
CREATE INDEX IF NOT EXISTS idx_attach_visit ON attachments(visit_id);
CREATE INDEX IF NOT EXISTS idx_attach_case ON attachments(inpatient_case_id);

-- ============================================================ POINT OF SALE (Retail only)
CREATE TABLE IF NOT EXISTS sales (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_date TEXT NOT NULL,  -- actually a full timestamp (datetime.now().isoformat()), not date-only -- see note in data_integrity_framework.md
    cashier_id TEXT,
    subtotal DOUBLE PRECISION NOT NULL,
    discount_percent DOUBLE PRECISION NOT NULL DEFAULT 0,
    discount_applied_by TEXT,
    total DOUBLE PRECISION NOT NULL,
    payment_method TEXT,
    -- Only populated for Cash sales — the cash physically handed over and
    -- the change handed back (already floored to the nearest 250 IQD
    -- note). NULL for any other payment method.
    cash_received DOUBLE PRECISION,
    change_given DOUBLE PRECISION,
    FOREIGN KEY (cashier_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS sale_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id INTEGER NOT NULL,
    item_id TEXT NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    unit_price DOUBLE PRECISION NOT NULL,
    line_total DOUBLE PRECISION NOT NULL,
    -- Cost snapshotted at sale time, alongside the row lock in
    -- pos_checkout — this is what lets COGS reporting reflect the actual
    -- cost basis of each sale instead of re-reading current inventory
    -- cost (which would retroactively change a past month's COGS every
    -- time an item's cost is edited). Nullable: an item without a
    -- cost_price set has nothing to snapshot.
    unit_cost DOUBLE PRECISION,
    FOREIGN KEY (sale_id) REFERENCES sales(id),
    FOREIGN KEY (item_id) REFERENCES inventory_list(id)
);
CREATE INDEX IF NOT EXISTS idx_saleitems_sale ON sale_items(sale_id);

-- ============================================================ REFUNDS (Admin only)
-- Two kinds: 'retail' (one or more products returned, identified by barcode,
-- with an option to put the stock back) and 'service' (a straight revenue
-- reduction against a Visit or Inpatient case, no stock impact). Both reduce
-- revenue in the P&L for the month the refund itself was processed in —
-- not the original sale/visit's month — matching normal accounting practice.
CREATE TABLE IF NOT EXISTS refunds (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_type TEXT NOT NULL CHECK (refund_type IN ('retail','service')),
    refund_date DATE NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    restocked BOOLEAN NOT NULL DEFAULT FALSE,   -- retail only: were the returned items put back into inventory?
    visit_id TEXT,                          -- service only, optional link
    inpatient_case_id INTEGER,              -- service only, optional link
    reason TEXT,
    processed_by TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (visit_id) REFERENCES visits(id),
    FOREIGN KEY (inpatient_case_id) REFERENCES inpatient_cases(id)
);
CREATE INDEX IF NOT EXISTS idx_refunds_date ON refunds(refund_date);

CREATE TABLE IF NOT EXISTS refund_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_id INTEGER NOT NULL,
    item_id TEXT NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    unit_price DOUBLE PRECISION NOT NULL,
    line_total DOUBLE PRECISION NOT NULL,
    FOREIGN KEY (refund_id) REFERENCES refunds(id),
    FOREIGN KEY (item_id) REFERENCES inventory_list(id)
);
CREATE INDEX IF NOT EXISTS idx_refunditems_refund ON refund_items(refund_id);

-- ============================================================ OPEX / P&L (monthly is the source; yearly rolls it up)
CREATE TABLE IF NOT EXISTS monthly_opex (
    month TEXT PRIMARY KEY,           -- 'YYYY-MM'
    rent DOUBLE PRECISION NOT NULL DEFAULT 0,
    salaries DOUBLE PRECISION NOT NULL DEFAULT 0,
    utilities DOUBLE PRECISION NOT NULL DEFAULT 0,
    marketing DOUBLE PRECISION NOT NULL DEFAULT 0,
    other DOUBLE PRECISION NOT NULL DEFAULT 0
);

-- Materialized per-month revenue/COGS, kept in sync incrementally by app.py
-- on every write that affects it (new sale, billing, refund, boarding total,
-- inpatient billing/discount, etc.) and fully rebuilt by
-- logic.recompute_full_summary() whenever a shared Price List / Inventory
-- Catalog cost or sale price changes, since those can retroactively affect
-- COGS/revenue for many past months at once. This is what lets Monthly &
-- Yearly P&L load instantly regardless of how many historical
-- billing/sales/refund rows exist, instead of re-scanning all of them on
-- every page view.
CREATE TABLE IF NOT EXISTS monthly_financial_summary (
    month TEXT PRIMARY KEY,           -- 'YYYY-MM'
    revenue DOUBLE PRECISION NOT NULL DEFAULT 0,
    cogs DOUBLE PRECISION NOT NULL DEFAULT 0,
    updated_at TEXT
);

-- ============================================================ APPOINTMENTS
-- Slot grid is generated dynamically from settings (appt_start_time / appt_end_time /
-- appt_slot_minutes) — no fixed slot table needed; slot labels (each slot's own start
-- time, e.g. '09:00', '09:30'...) are derived at render time from that range.
CREATE TABLE IF NOT EXISTS appointments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appt_date DATE NOT NULL,
    slot_label TEXT NOT NULL,          -- the slot's start time, e.g. '09:00', '09:30'...
    resource_type TEXT NOT NULL CHECK (resource_type IN ('vet','grooming')),
    resource_id TEXT,                  -- users.id when resource_type='vet'; NULL for grooming
    pet_name TEXT NOT NULL,
    owner_name TEXT NOT NULL,
    appointment_type TEXT NOT NULL CHECK (appointment_type IN ('Medical','Grooming')),
    reason TEXT,
    created_by TEXT,
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_appt_date ON appointments(appt_date);

-- Enforces at the database level what logic.slot_conflict() only checks at
-- the application level: two appointments can't occupy the same slot for
-- the same vet/groomer. The app-level check-then-insert alone has a race
-- window — two concurrent bookings for the same slot can both pass the
-- check before either inserts. COALESCE(resource_id, '') is needed because
-- resource_id is NULL for grooming rows, and Postgres otherwise treats
-- every NULL as distinct under a plain UNIQUE constraint (which would let
-- unlimited grooming appointments stack into the same slot).
CREATE UNIQUE INDEX IF NOT EXISTS uq_appointments_slot
    ON appointments (appt_date, slot_label, resource_type, COALESCE(resource_id, ''));


-- ============================================================ BILLING SNAPSHOTS
-- Revenue/COGS reporting reads *current* Price List / Inventory Catalog
-- values only where nothing was sold/billed yet; once a line is
-- sold/billed, its price and cost are snapshotted here (or in
-- inpatient_billing.unit_price/unit_cost, sale_items.unit_cost above) so
-- a later price edit can never reach back and change a transaction that
-- already happened. Automatic visit billing is driven entirely by these
-- rows (price_id + quantity, added via the search-and-add billing UI) —
-- there's no comma-string intermediate anymore (billing.codes was
-- removed once this became the only way an Automatic bill gets built).
CREATE TABLE IF NOT EXISTS visit_billing_lines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id TEXT NOT NULL,
    price_id TEXT NOT NULL,
    name TEXT NOT NULL,
    category TEXT,
    quantity DOUBLE PRECISION NOT NULL DEFAULT 1,
    unit_price DOUBLE PRECISION NOT NULL,
    unit_cost DOUBLE PRECISION,
    created_at TEXT NOT NULL,
    FOREIGN KEY (visit_id) REFERENCES visits(id),
    FOREIGN KEY (price_id) REFERENCES price_list(id)
);
CREATE INDEX IF NOT EXISTS idx_visit_billing_lines_visit ON visit_billing_lines(visit_id);


-- ============================================================ CONSIGNMENT
-- A distributor's stock, sitting on your shelf: they're owed cost_price
-- per unit once it sells; you keep the markup. Consignment items are
-- ordinary Retail inventory_list rows (ownership_type='Consignment',
-- above) — they flow through the existing POS/audit/P&L pipeline
-- unmodified (see logic.py's consignment_* functions and
-- Consignment_Feature_Framework.md §2). These four tables are the
-- distributor-facing receiving/shrinkage/returns/settlement layer on top
-- of that shared data, not a second inventory system.

-- Stock the distributor drops off. Paired with an inventory_transactions
-- row (reason='consignment_receipt', +quantity) at insert time — see
-- logic.record_consignment_receipt() — so new stock is immediately
-- visible on Inventory Status and the next audit walk, same mechanism
-- POS checkout and refund restocking already use.
CREATE TABLE IF NOT EXISTS consignment_receipts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id TEXT NOT NULL,
    distributor_id TEXT NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    unit_cost_at_receipt DOUBLE PRECISION NOT NULL,
    received_date DATE NOT NULL,
    delivery_reference TEXT,
    notes TEXT,
    received_by TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (item_id) REFERENCES inventory_list(id),
    FOREIGN KEY (distributor_id) REFERENCES distributors(id),
    FOREIGN KEY (received_by) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_consreceipts_item ON consignment_receipts(item_id);
CREATE INDEX IF NOT EXISTS idx_consreceipts_dist ON consignment_receipts(distributor_id);

-- Damaged/expired consignment stock, written off before it ever sold.
-- Paired with an inventory_transactions row (reason='shrinkage',
-- -quantity) at insert time, same shelf-count effect as a sale — see
-- logic.record_consignment_shrinkage(). liable_party decides whether
-- this adds to what's owed the distributor (§9/§7): 'Clinic' does,
-- 'Distributor' doesn't (they absorb the stock loss directly).
CREATE TABLE IF NOT EXISTS consignment_shrinkage (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id TEXT NOT NULL,
    distributor_id TEXT NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    reason TEXT NOT NULL CHECK (reason IN ('Damaged','Expired','Other')),
    liable_party TEXT NOT NULL CHECK (liable_party IN ('Distributor','Clinic')),
    liability_overridden BOOLEAN NOT NULL DEFAULT FALSE,
    unit_cost DOUBLE PRECISION NOT NULL,
    notes TEXT,
    logged_by TEXT,
    logged_at TEXT NOT NULL,
    FOREIGN KEY (item_id) REFERENCES inventory_list(id),
    FOREIGN KEY (distributor_id) REFERENCES distributors(id),
    FOREIGN KEY (logged_by) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_consshrink_item ON consignment_shrinkage(item_id);
CREATE INDEX IF NOT EXISTS idx_consshrink_dist ON consignment_shrinkage(distributor_id);

-- Unsold stock physically handed back to the distributor — mirror image
-- of Receiving. Paired with an inventory_transactions row
-- (reason='consignment_return', -quantity) at insert time — see
-- logic.record_consignment_return(). No revenue/COGS/settlement impact:
-- nothing sold, so nothing owed either way; this never appears in
-- consignment_balance()'s formula (§7).
CREATE TABLE IF NOT EXISTS consignment_returns (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id TEXT NOT NULL,
    distributor_id TEXT NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    unit_cost_at_return DOUBLE PRECISION NOT NULL,
    return_date DATE NOT NULL,
    reason TEXT,
    notes TEXT,
    returned_by TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (item_id) REFERENCES inventory_list(id),
    FOREIGN KEY (distributor_id) REFERENCES distributors(id),
    FOREIGN KEY (returned_by) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_consreturns_item ON consignment_returns(item_id);
CREATE INDEX IF NOT EXISTS idx_consreturns_dist ON consignment_returns(distributor_id);

-- A record of "paid the distributor for what's sold since we last
-- settled." amount_paid may be less than amount_owed (a confirmed
-- partial settlement) — the difference carries forward as the next
-- settlement's starting residual (see logic.consignment_balance, §7).
CREATE TABLE IF NOT EXISTS consignment_settlements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    distributor_id TEXT NOT NULL,
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    amount_owed DOUBLE PRECISION NOT NULL,
    amount_paid DOUBLE PRECISION NOT NULL,
    payment_method TEXT,
    notes TEXT,
    settled_by TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (distributor_id) REFERENCES distributors(id),
    FOREIGN KEY (settled_by) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_conssettle_dist ON consignment_settlements(distributor_id);


